name: SmartAlarm
channels:
  - defaults
dependencies:
  - pip
  - python=3.6
  - setuptools
  - sqlite
  - wheel
  - zlib
  - pip:
    - adafruit-blinka
    - adafruit-circuitpython-busdevice
    - adafruit-circuitpython-dotstar
    - adafruit-circuitpython-pypixelbuf
    - adafruit-platformdetect
    - adafruit-pureio
    - beautifulsoup4
    - bs4
    - cachetools
    - certifi
    - chardet
    - click
    - comtypes
    - cycler
    - dataclasses
    - enum34
    - flask==1.1.2
    - future
    - google==3.0.0
    - google-api-core==1.26.0
    - google-auth==1.27.0
    - google-cloud==0.34.0
    - google-cloud-texttospeech==2.2.0
    - googleapis-common-protos==1.52.0
    - grpcio==1.35.0
    - idna==2.10
    - itsdangerous==1.1.0
    - jinja2==2.11.3
    - kiwisolver==1.3.1
    - libcst==0.3.17
    - markupsafe==1.1.1
    - mypy-extensions
    - numpy
    - packaging
    - pandas
    - pillow
    - proto-plus
    - protobuf==3.15.1
    - psutil==5.8.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyaudio==0.2.11
    - pycaw==20181226
    - pydub==0.24.1
    - pyftdi==0.52.9
    - pyparsing==2.4.7
    - pyserial==3.5
    - python-dateutil==2.8.1
    - pytz==2021.1
    - pyusb==1.1.1
    - pyyaml==5.4.1
    - requests==2.25.1
    - rsa==4.7.1
    - scipy==1.5.4
    - six==1.15.0
    - soupsieve==2.2
    - tinytag==1.5.0
    - typing-extensions==3.7.4.3
    - typing-inspect==0.6.0
    - urllib3==1.26.3
    - werkzeug==1.0.1

