name: SmartAlarm
channels:
  - defaults
dependencies:
  - pip
  - python=3.6
  - setuptools
  - sqlite
  - wheel
  - zlib
  - pandas
  - numpy
  - pyaudio
  - bs4
  - flask
  - scipy
  - pyyaml
  - google-cloud-texttospeech
  - pip:
    - adafruit-blinka
    - adafruit-circuitpython-busdevice
    - adafruit-circuitpython-dotstar
    - adafruit-circuitpython-pypixelbuf
    - adafruit-platformdetect
    - adafruit-pureio
    - certifi
    - chardet
    - comtypes
    - cycler
    - enum34
    - future
    - grpcio==1.35.0
    - kiwisolver==1.3.1
    - libcst==0.3.17
    - mypy-extensions
    - packaging
    - pillow
    - proto-plus
    - psutil==5.8.0
    - pyaudio==0.2.11
    - pycaw==20181226
    - pydub==0.24.1
    - pyftdi==0.52.9
    - pyserial==3.5
    - pytz==2021.1
    - pyusb==1.1.1
    - scipy==1.5.4
    - six==1.15.0
    - soupsieve==2.2
    - tinytag==1.5.0
    - typing-extensions==3.7.4.3
    - typing-inspect==0.6.0


