name: SmartAlarm
channels:
  - defaults
  - rpi
dependencies:
  - pip
  - python=3.6
  - setuptools
  - sqlite
  - wheel
  - zlib
  - pandas
  - numpy
  - pip:
    - adafruit-blinka
    - adafruit-circuitpython-busdevice
    - adafruit-circuitpython-dotstar
    - adafruit-circuitpython-pypixelbuf
    - adafruit-platformdetect
    - adafruit-pureio
    - certifi
    - chardet
    - comtypes
    - google-cloud-texttospeech
    - cycler
    - bs4
    - enum34
    - future
    - grpcio
    - kiwisolver==1.3.1
    - libcst==0.3.17
    - mypy-extensions
    - packaging
    - proto-plus
    - psutil==5.8.0
    - pyaudio==0.2.11
    - pycaw==20181226
    - flask
    - pydub==0.24.1
    - python-dateutil>=2.5.0
    - pyftdi==0.52.9
    - pyserial==3.5
    - pytz
    - pyusb==1.1.1
    - six==1.15.0
    - soupsieve==2.2
    - tinytag==1.5.0
    - typing-extensions==3.7.4.3
    - typing-inspect==0.6.0


